name: Fly Deploy - Core
on:
   push:
      branches:
         - main

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
   deploy:
      name: Deploy core app
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: superfly/flyctl-actions/setup-flyctl@master
         - run: flyctl deploy --app "$APP_NAME" --config ./fly/fly.core.toml --depot=false
           env:
              FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              APP_NAME: ${{ secrets.APP_NAME }}
